### ISSUE TITLE
Nuget package restore fails

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/setup-msbuild#47] opened 2021-04-07 04:33 UTC
Restoring nuget packages via `MSBuild` (`msbuild $env:SOLUTION_NAME /t:Restore`) [fails](https://github.com/JasonStein/Notepads/runs/2283687678?check_suite_focus=true) with error `NU1101` while package restore [succeeds](https://github.com/JasonStein/Notepads/pull/854/checks?check_run_id=2284261379) with `nuget.exe` (`nuget restore $env:SOLUTION_NAME`). This issue is happening recently.

**Comment by timheuer** [comment] 2021-04-09 02:12
Hi @soumyamahunt this does not appear to be an issue with this action but rather with MSBuild and your configuration specifically.  This action would use the latest Visual Studio version of MSBuild which may be causing an unexpected change if your local environment works as expected.

**Comment by timheuer** [comment] 2021-04-10 17:13
This looks like it is hitting the cause here: https://github.com/actions/virtual-environments/issues/3038 -- I'm closing this issue on this repo as it isn't related to this Action, but a workaround is suggested on the 3038 issue referenced here.

**Closed by timheuer** 2021-04-10 17:13 UTC
Labels: ❓ needs-more-info

**Comment by soumyamahunt** [comment] 2021-04-11 15:39
> This looks like it is hitting the cause here: [actions/virtual-environments#3038](https://github.com/actions/virtual-environments/issues/3038) -- I'm closing this issue on this repo as it isn't related to this Action, but a workaround is suggested on the 3038 issue referenced here.

Thanks I would stick to using `Nuget.exe` to restore packages as I am also staring to include some C++ projects in my solution and `msbuild` doesn't restore packages for those projects.

Since the default nuget config file is quite generic can't this be restored by this action or it is not possible or out of scope?

**Comment by timheuer** [comment] 2021-04-12 16:13
Yes default nuget.config is indeed generic, but that is out of scope for this action which is to really find msbuild.exe for the action that's it.  Many people do things differently and we wouldn't want this action to start doing nuget-y things.
