### ISSUE TITLE
Release a new version (with the recent updates, most notably @actions/core)

### ISSUE THREAD

**Issue by dscho** [microsoft/setup-msbuild#27] opened 2020-10-06 15:49 UTC
As per https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/, there is currently a nasty warning for every user of this Action:

> ##[warning]The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

See for example https://github.com/git-for-windows/git/actions/runs/291669581.

The solution proposed in that blog post is to upgrade `@actions/core` to at least v1.2.6, which has been done in the main branch already, but there is no official version with that fix yet.

**Comment by timheuer** [comment] 2020-10-06 15:54
Dupe of #26

**Closed by timheuer** 2020-10-06 15:54 UTC

**Comment by timheuer** [comment] 2020-10-06 16:02
@dscho you logged this right as I was processing the release ;-) -- it's now been independently released as v1.0.2 and the v1 tag has been updated to point to this ref
