### ISSUE TITLE
Usage of `add-path` fail

### ISSUE THREAD

**Issue by bourne-xian** [microsoft/setup-msbuild#36] opened 2020-11-26 07:21 UTC
![Setup MSBuild path fail](https://user-images.githubusercontent.com/74710215/100319137-1ecccd80-2ffa-11eb-8345-fa53e7948743.png)

It may related to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Any advise? Thanks, have a nice day.

**Comment by KaustubhPatange** [comment] 2020-11-26 13:29
I've proposed PR #37 which fixes this issue. In the meantime, you can use my fork of this action from [here](https://github.com/KaustubhPatange/setup-msbuild).

**Comment by timheuer** [comment] 2020-11-26 16:51
This has already been fixed in v1.0.2 two months ago dupe of #26

**Closed by timheuer** 2020-11-26 16:51 UTC
