### ISSUE TITLE
Support using 64-bit MSBuild

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/setup-msbuild#64] opened 2021-10-18 20:51 UTC
MSBuild in Visual Studio ships with two `MSBuild.exe` entry points: the `MSBuild\Current\bin` folder has an x86 (32-bit) executable, and `MSBuild\Current\bin\amd64` has a 64-bit (x64/amd64) executable.

In general, both can build any type of project, but some codebases benefit from the increased memory capacity of the 64-bit version.

The 32-bit MSBuild has been on `PATH` in the Developer Command Prompt in Visual Studio 2019 and prior, but Visual Studio 2022 puts 64-bit MSBuild on `PATH` to match Visual Studio which is now 64-bit.

This Action should expose an option to put 64-bit MSBuild on `PATH` instead of 32-bit. Azure DevOps has an option to do so in its [MSBuild task](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops):

> <table><tr>
>      <td><code>msbuildArchitecture</code><br/>MSBuild Architecture</td>
>      <td>(Optional) Optionally supply the architecture (x86, x64) of MSBuild to run<br/>Default value: x86</td>
>   </tr></table>

For compatibility I would recommend keeping x86 the default; ideally that might change at some point in the future.

**Comment by timheuer** [comment] 2021-10-18 20:59
Thanks @rainersigwald! In VS2022, there is only one arch right, we don't ship both x86 and x64 in that build?

The reason I ask is most customers are using hosted agents which will only have 1 version of VS on them at any given time (at least at present by design of the hosted agents).

I'm not sure how the task implemented it (will look) but we're using `vswhere` here -- @heaths does vswhere easily accommodate adding arch-specific searching?

**Comment by rainersigwald** [comment] 2021-10-18 21:02
We continue to ship both and in the same relative positions--all that changed is the entry on PATH in the dev command prompt. So this will work as-is but potentially diverge from desktop builds if folks use the dev command prompt.

This is the relevant snipped here:

https://github.com/microsoft/setup-msbuild/blob/0cd944e169acbc0583c24158d0723223ff302513/src/main.ts#L73-L77

**Comment by rainersigwald** [comment] 2021-10-18 21:07
That makes sense to me, yeah.

**Comment by timheuer** [comment] 2021-11-02 03:08
Fixed with #65 merge and released in `v1.1` tag -- marketplace updated

**Closed by timheuer** 2021-11-02 03:08 UTC
Labels: enhancement, help wanted
